ALTER TABLE event ADD COLUMN color_mode VARCHAR(10) NOT NULL DEFAULT 'DARK';
ALTER TABLE event ADD COLUMN background_position_x DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE event ADD COLUMN background_position_y DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE event ADD COLUMN background_fit VARCHAR(10) NOT NULL DEFAULT 'COVER';
